spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 90084769423-ot70g1qd3en554bu9tj60ff2cj4i0gbh.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile